module DieRoll
  VERSION: String
  MINIMUM_DIE_SIZE: Integer
  DICE_SYNTAX_REGEX: Regexp

  class ParseError < StandardError
  end

  class DieSizeError < StandardError
  end

  class Roll
    attr_reader sides: Array[String]
    attr_reader values: Array[Integer]

    def initialize: (sides: Integer, values: Array[Integer]) -> void
    def total: -> Integer
  end

  class Parser
    attr_reader tokens: Array[String]

    def initialize: (String) -> void

    private
    def generate_tokens: (String) -> void
    def validate_tokens: -> void
  end

  class Roller
    def self.roll: (Parser parser) -> Array[Roll]
  end

  class Result
    attr_reader tokens: Array[String]

    def initialize: (rolls: Array[Roll], tokens: Array[String]) -> void
    def total: -> Integer
  end
end
